### ISSUE TITLE
release kargo-render binary

### ISSUE THREAD

**Issue by joaoestrela** [akuity/kargo-render#284]
Currently, only the Docker image is published. It would be great to also provide a binary release. Currently, it's challenging to pass through Helm credentials in a GitHub Action because it's within a container with its own Helm installation.

Having a binary release would allow the `kargo-render` binary to be used within the workflow authentication context.

**Comment by krancour** [comment]
> Currently, it's challenging to pass through Helm credentials in a GitHub Action because it's within a container with its own Helm installation.

Kargo proper just did something about this a few days ago: https://github.com/akuity/kargo/pull/1977

I had been imagining that we'd soon create a native way for chart repo creds to be passed directly to Kargo Render as well, but hadn't yet put much thought into _how_.

On some level, I'd prefer solving that over simply publishing the binary, since there is a reason that we don't. (Packaging it in an image with git, helm, and kustomize binaries is the easiest way to _guarantee_ Kargo Render has compatible versions of those binaries available to it.)

I'll start thinking about a clean way of passing the creds through.

**Comment by joaoestrela** [comment]
Fair points.
My suggestion was intended as an additional option for those who might prefer a more customised approach, but I guess that compiling it themselves is a viable solution.
Thanks!

**Comment by krancour** [comment]
> compiling it themselves is a viable solution

You can also copy it out of a container as long as you're looking for linux/amd64 (or linux/arm64). Presumably in an Action, linux/amd64 would be exactly what you need.

**Comment by krancour** [comment]
To put some closure on this, solving for #226 will obviate the need for this.
